name: coding challenge test

on: [push]
  jobs:
    build:

      runs-on: ubuntu-latest
      strategy:
        matrix:
          python: ["3.8"]
      steps:
        - uses: actions/checkout@v3
        - name: Checkout and Setup
          with:
            python-version: ${{matrix.python}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Test with pytest
          run: | 
            pip install pytest
            pytests test_integration.py